[package]
name = "lineup"
version = "0.1.0"
authors = ["OverHash <46231745+OverHash@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.5.5"
